#!/usr/bin/env python3

from __future__ import with_statement
import contextlib
import os
import sys
import subprocess
import time

shmThreshold = 85.0

while True:
	with contextlib.closing(open('/etc/mtab')) as fp:
		for m in fp: 
			fs_spec, fs_file, _1, _2, _3, _4 = m.split()
			if fs_spec.startswith(''):
		  		r = os.statvfs(fs_file)

			if r.f_bavail == 0:
				continue

			block_usage_pct = 100.0 - (float(r.f_bavail) / float(r.f_blocks) * 100)
			inode_usage_pct = 100.0 - (float(r.f_favail) / float(r.f_files) * 100)

			#print(fs_spec + " " + fs_file + " " + str(block_usage_pct) + "% " + str(inode_usage_pct) + "% ")

			if str(fs_file).find("/shm") != -1:
				if block_usage_pct >= shmThreshold or inode_usage_pct >= shmThreshold:
					subprocess.Popen("killall -9 kesl", shell = True).wait()
	time.sleep(60)