#include "../../inc/BCdata_restorator.h"
#include <vector>

const char* bulletsFile = "{"
"    \"current_bullet_index\": 0,"
"    \"bullets\": ["
"        {"
"            \"name\": \"LPS\","
"            \"DF\": \"G7\","
"            \"BC\": 0.206,"
"            \"MV\": 830,"
"            \"length\": 32.3,"
"            \"weight\": 148,"
"            \"caliber\": 7.92,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 0.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"7N1(7N14)\","
"            \"DF\": \"G7\","
"            \"BC\": 0.211,"
"            \"MV\": 830,"
"            \"length\": 32.6,"
"            \"weight\": 151,"
"            \"caliber\": 7.92,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 0.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"Bullet D\","
"            \"DF\": \"G7\","
"            \"BC\": 0.236,"
"            \"MV\": 780,"
"            \"length\": 32.2,"
"            \"weight\": 182,"
"            \"caliber\": 7.92,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 0.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"7N34\","
"            \"DF\": \"G7\","
"            \"BC\": 0.481,"
"            \"MV\": 775,"
"            \"length\": 65.3,"
"            \"weight\": 903,"
"            \"caliber\": 13.1,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 1.9,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"B-32(12.7mm)\","
"            \"DF\": \"G7\","
"            \"BC\": 0.399,"
"            \"MV\": 800,"
"            \"length\": 63.9,"
"            \"weight\": 742,"
"            \"caliber\": 13.1,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 3.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"SMK 168 gr.\","
"            \"DF\": \"G7\","
"            \"BC\": 0.218,"
"            \"MV\": 805,"
"            \"length\": 30.8,"
"            \"weight\": 168,"
"            \"caliber\": 7.82,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 0.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"NCC 168 gr.\","
"            \"DF\": \"G7\","
"            \"BC\": 0.218,"
"            \"MV\": 840,"
"            \"length\": 30.1,"
"            \"weight\": 168,"
"            \"caliber\": 7.82,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 0.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"NDD 168 gr.\","
"            \"DF\": \"G7\","
"            \"BC\": 0.236,"
"            \"MV\": 740,"
"            \"length\": 31,"
"            \"weight\": 168,"
"            \"caliber\": 7.82,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 0.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"SMK 250 gr.\","
"            \"DF\": \"G7\","
"            \"BC\": 0.314,"
"            \"MV\": 850,"
"            \"length\": 39.5,"
"            \"weight\": 250,"
"            \"caliber\": 8.6,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 1.7,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        },"
"        {"
"            \"name\": \"LSC 250 gr.\","
"            \"DF\": \"G7\","
"            \"BC\": 0.322,"
"            \"MV\": 875,"
"            \"length\": 39.5,"
"            \"weight\": 250,"
"            \"caliber\": 8.6,"
"            \"MV_temp.\": 15,"
"            \"therm.sens.\": 1.5,"
"            \"CF_M0.9\": 1,"
"            \"CF_M1.0\": 1,"
"            \"CF_M1.1\": 1"
"        }"
"    ]"
"}";

const char* riflesFile = "{"
"	\"current_rifle_index\": 0,"
"	\"rifles\": ["
"		{"
"			\"name\": \"SVD-240\","
"			\"scope_hight\": 5,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 240,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"SV-98(M)\","
"			\"scope_hight\": 5,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 320,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"ASVK(KORD)\","
"			\"scope_hight\": 5,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 420,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"SSG-08(.308)\","
"			\"scope_hight\": 5,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 255,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"SSG-08(.338)\","
"			\"scope_hight\": 5,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 229,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"User #1\","
"			\"scope_hight\": 7,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 305,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"User #2\","
"			\"scope_hight\": 7,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 305,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"User #3\","
"			\"scope_hight\": 7,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 305,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"User #4\","
"			\"scope_hight\": 7,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 305,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		},"
"		{"
"			\"name\": \"User #5\","
"			\"scope_hight\": 7,"
"			\"zero_dist.\": 100,"
"			\"zero_vert.drift\": 0,"
"			\"zero_vert.drify.dir.\": \"up\","
"			\"zero_horiz.drift\": 0,"
"			\"zero_horiz.drift.dir\": \"left\","
"			\"scope_units\": \"MRAD\","
"			\"vert.click\": 0.1,"
"			\"horiz.click\": 0.1,"
"			\"twist\": 305,"
"			\"twist_dir.\": \"right\","
"			\"zeroing\": \"here\","
"			\"zero_T\": 15,"
"			\"zero_P\": 1000"
"		}"
"	]"
"}";

const char* settingsFile = R"({
	"bckl.intens.": 127,
	"bckl.fade_sec": 60,
	"autooff_min": 3,
	"latitude": 55.4521,
	"magnetic.incl.": 4
})";

const char* inputsFile = R"({
    "koriolis": false,
    "termocorr.": false,
    "range_card": false,
    "aero_jump": false
})";

const char* targetFile = R"({
	"distance": 600,
	"terrain_angle": 15,
	"speed_mils": 0,
	"azimuth": 0
})";

const char* mildotFile = R"({
	"size": 1.8,
	"mils": 2.8
})";

namespace restore {

	const std::vector<std::pair<const char*, const char*>> data {
		
		{BULLETS_DATAFILE, bulletsFile},
		{RIFLES_DATAFILE, riflesFile},
		{SETTINGS_DATAFILE, settingsFile},
		{INPUTS_DATAFILE, inputsFile},
		{TARGET_DATAFILE, targetFile},
		{MILDOT_DATAFILE, mildotFile}
	};
}

bool dataRestorator::saveConfigFile(const std::pair<const char*, const char*>& config) {

	auto path = config.first;
	auto content = config.second;

	auto file = SPIFFS.open(path, "w");

	if(!file) {
		return false;
	}
	
	file.print(content);
	file.close();
	return true;
}

bool dataRestorator::formatAndRestore() {

	SPIFFS.format();

	for(const auto config : restore::data) {

		if(!dataRestorator::saveConfigFile(config)) {
			return false;
		}
	}
	return true;
}